version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: hand-market-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis
    restart: always
    container_name: hard-market-redis
    environment:
      REDIS_PASSWORD: "1234"
    ports:
      - "6379:6379"

