version: '3'
services:
  postgresql:
      image: postgres
      container_name: hand-market-postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DATABASES=hand-market
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
  redis:
    image: redis
    restart: always
    container_name: hard-market-redis
    environment:
      REDIS_PASSWORD: "1234"
    ports:
      - "6379:6379"
volumes:
  postgres_data:
